import { CartSchema } from '../../schemas';

export const cartMock: CartSchema = {
  buyableItemCount: 1,
  totalPrice: {
    salesPrice: 76000,
    shippingCost: 0,
    orderPrice: 76000,
  },
  cartItemList: [
    {
      provider: {
        id: 21206,
        name: '(주) 스티키몬스터랩',
      },
      shippingGroupList: [
        {
          provider: {
            id: 21206,
            name: '(주) 스티키몬스터랩',
          },
          brandGroupList: [
            {
              brand: {
                id: 21204,
                name: '스티키몬스터랩',
                primaryImage: {
                  id: 24842,
                  path: 'brand/20220222/e2f125dc-9bae-42e6-9a73-c6fb31bc863c.svg',
                  blurHash: null,
                  width: 58,
                  height: 24,
                },
                defaultShowRoomId: null,
                brandShowRoomCode: 'sml',
              },
              cartDataList: [
                {
                  cartId: 21223,
                  provider: {
                    id: 21206,
                    name: '(주) 스티키몬스터랩',
                  },
                  brand: {
                    id: 21204,
                    name: '스티키몬스터랩',
                    primaryImage: {
                      id: 24842,
                      path: 'brand/20220222/e2f125dc-9bae-42e6-9a73-c6fb31bc863c.svg',
                      blurHash: null,
                      width: 58,
                      height: 24,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 21217,
                    name: '[스티키몬스터랩] BABY LAMP 01',
                    primaryImage: {
                      id: 21486,
                      path: 'goods/20220211/1563660a-dd3d-44df-a743-238eee61d9d3.jpeg',
                      blurHash:
                        '|RSPU.t7_NxuD$oft7xuog%MjtM{a|ofj[ofa|WB%Nj[IUayxuj[WBayWBj[j[t6ayayj[WBfQofxufQRPa|t7j[WBayj[j[fQofj[ayayaxj[j[t7j[WBayfQj[offQayoLayozj[WBayj[j@ayWBfQoff6aefQfQj[j[',
                      width: 480,
                      height: 473,
                    },
                    consumerPrice: 38000,
                    price: 38000,
                    discountRate: 0,
                    showRoomId: 0,
                    code: 'ic1y0',
                    label: null,
                    goodsStatusText: '판매중',
                    option: {
                      id: 21353,
                      itemList: [
                        {
                          title: '옵션명',
                          value: '[스티키몬스터랩] BABY LAMP 01',
                        },
                      ],
                    },
                    packageOption: null,
                  },
                  purchasableStock: 100,
                  quantity: 2,
                  consumerPriceWithQuantity: 76000,
                  priceWithQuantity: 76000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'delivery21205',
                },
              ],
            },
          ],
          shippingGroupName: 'delivery21205',
          shippingPolicyText: '50,000원 이상 무료배송',
          price: {
            salesPrice: 76000,
            shippingCost: 0,
            orderPrice: 76000,
          },
        },
      ],
    },
  ],
};

export const calculate = {
  totalSalesPrice: 926000,
  totalShippingCost: 2500,
  orderPrice: 928500,
  cartItemList: [
    {
      provider: { id: 45, name: '나이키' },
      shippingGroupList: [
        {
          provider: { id: 45, name: '나이키' },
          brandGroupList: [
            {
              brand: {
                id: 2,
                name: 'nike',
                primaryImage: {
                  id: 10526,
                  path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
                  blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
                  width: 150,
                  height: 40,
                },
                defaultShowRoomId: null,
                brandShowRoomCode: 'nikeshowroom',
              },
              cartDataList: [
                {
                  cartId: 559,
                  provider: { id: 45, name: '나이키' },
                  showRoomId: 0,
                  brand: {
                    id: 2,
                    name: 'nike',
                    primaryImage: {
                      id: 10526,
                      path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
                      blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
                      width: 150,
                      height: 40,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 148,
                    name: '21ss 나이키 긴팔 티셔츠',
                    primaryImage: {
                      id: 100,
                      path: 'goods/20210701/8228ef3d-4ef1-4547-bf23-f5bfe99c8672',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 30000,
                    price: 25000,
                    discountRate: 17,
                    goodsStatusText: '판매중',
                    option: {
                      id: 334,
                      itemList: [
                        { title: '치수', value: 'S' },
                        { title: 'color', value: '블랙' },
                      ],
                    },
                    packageOption: null,
                  },
                  quantity: 1,
                  consumerPriceWithQuantity: 30000,
                  priceWithQuantity: 25000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'delivery22',
                },
              ],
            },
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
                brandShowRoomCode: 'likenike',
              },
              cartDataList: [
                {
                  cartId: 531,
                  provider: { id: 45, name: '나이키' },
                  showRoomId: 0,
                  brand: {
                    id: 3,
                    name: '노스페이스',
                    primaryImage: {
                      id: 1,
                      path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                      blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                      width: 200,
                      height: 300,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 150,
                    name: '21ss 나이키 패딩',
                    primaryImage: {
                      id: 106,
                      path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 30000,
                    price: 25000,
                    discountRate: 17,
                    goodsStatusText: '판매중',
                    option: {
                      id: 370,
                      itemList: [
                        { title: '사이즈', value: '95' },
                        { title: '색상', value: '화이트' },
                      ],
                    },
                    packageOption: null,
                  },
                  quantity: 3,
                  consumerPriceWithQuantity: 90000,
                  priceWithQuantity: 75000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'delivery22',
                },
                {
                  cartId: 523,
                  provider: { id: 45, name: '나이키' },
                  showRoomId: 0,
                  brand: {
                    id: 3,
                    name: '노스페이스',
                    primaryImage: {
                      id: 1,
                      path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                      blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                      width: 200,
                      height: 300,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 150,
                    name: '21ss 나이키 패딩',
                    primaryImage: {
                      id: 106,
                      path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 30000,
                    price: 25000,
                    discountRate: 17,
                    goodsStatusText: '판매중',
                    option: {
                      id: 372,
                      itemList: [
                        { title: '사이즈', value: '105' },
                        { title: '색상', value: '화이트' },
                      ],
                    },
                    packageOption: null,
                  },
                  quantity: 1,
                  consumerPriceWithQuantity: 30000,
                  priceWithQuantity: 25000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'delivery22',
                },
              ],
            },
          ],
          shippingGroupName: 'delivery22',
          shippingCost: 2500,
          shippingPolicyText: '2,500원',
          totalSalesPrice: 125000,
        },
        {
          provider: { id: 45, name: '나이키' },
          brandGroupList: [
            {
              brand: {
                id: 2,
                name: 'nike',
                primaryImage: {
                  id: 10526,
                  path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
                  blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
                  width: 150,
                  height: 40,
                },
                defaultShowRoomId: null,
                brandShowRoomCode: 'nikeshowroom',
              },
              cartDataList: [
                {
                  cartId: 528,
                  provider: { id: 45, name: '나이키' },
                  showRoomId: 0,
                  brand: {
                    id: 2,
                    name: 'nike',
                    primaryImage: {
                      id: 10526,
                      path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
                      blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
                      width: 150,
                      height: 40,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 175,
                    name: '나이키 조던4',
                    primaryImage: {
                      id: 109,
                      path: 'goods/20210701/90bca69d-a2a1-4d22-84c9-833d58eb8b5f',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 199000,
                    price: 199000,
                    discountRate: 0,
                    goodsStatusText: '판매중',
                    option: { id: 515, itemList: [{ title: '사이즈', value: '290' }] },
                    packageOption: null,
                  },
                  quantity: 1,
                  consumerPriceWithQuantity: 199000,
                  priceWithQuantity: 199000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'each_delivery175',
                },
                {
                  cartId: 529,
                  provider: { id: 45, name: '나이키' },
                  showRoomId: 0,
                  brand: {
                    id: 2,
                    name: 'nike',
                    primaryImage: {
                      id: 10526,
                      path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
                      blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
                      width: 150,
                      height: 40,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 175,
                    name: '나이키 조던4',
                    primaryImage: {
                      id: 109,
                      path: 'goods/20210701/90bca69d-a2a1-4d22-84c9-833d58eb8b5f',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 199000,
                    price: 199000,
                    discountRate: 0,
                    goodsStatusText: '판매중',
                    option: { id: 514, itemList: [{ title: '사이즈', value: '280' }] },
                    packageOption: null,
                  },
                  quantity: 2,
                  consumerPriceWithQuantity: 398000,
                  priceWithQuantity: 398000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'each_delivery175',
                },
                {
                  cartId: 530,
                  provider: { id: 45, name: '나이키' },
                  showRoomId: 0,
                  brand: {
                    id: 2,
                    name: 'nike',
                    primaryImage: {
                      id: 10526,
                      path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
                      blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
                      width: 150,
                      height: 40,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 175,
                    name: '나이키 조던4',
                    primaryImage: {
                      id: 109,
                      path: 'goods/20210701/90bca69d-a2a1-4d22-84c9-833d58eb8b5f',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 199000,
                    price: 199000,
                    discountRate: 0,
                    goodsStatusText: '판매중',
                    option: { id: 511, itemList: [{ title: '사이즈', value: '250' }] },
                    packageOption: null,
                  },
                  quantity: 1,
                  consumerPriceWithQuantity: 199000,
                  priceWithQuantity: 199000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'each_delivery175',
                },
              ],
            },
          ],
          shippingGroupName: 'each_delivery175',
          shippingCost: 0,
          shippingPolicyText: '무료배송',
          totalSalesPrice: 796000,
        },
      ],
      totalSalesPrice: 921000,
      totalShippingCost: 2500,
      orderPrice: 923500,
    },
    {
      provider: { id: 37, name: '아모레퍼시픽' },
      shippingGroupList: [
        {
          provider: { id: 37, name: '아모레퍼시픽' },
          brandGroupList: [
            {
              brand: {
                id: 15,
                name: '아모레퍼시픽',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
                brandShowRoomCode: 'asdfasdfa',
              },
              cartDataList: [
                {
                  cartId: 532,
                  provider: { id: 37, name: '아모레퍼시픽' },
                  showRoomId: 0,
                  brand: {
                    id: 15,
                    name: '아모레퍼시픽',
                    primaryImage: {
                      id: 1,
                      path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                      blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                      width: 200,
                      height: 300,
                    },
                    defaultShowRoomId: null,
                  },
                  goods: {
                    id: 144,
                    name: '설화수 스킨',
                    primaryImage: {
                      id: 108,
                      path: 'goods/20210701/6ae09d87-f8d7-4496-95c6-40859fd9845c',
                      blurHash: null,
                      width: 10,
                      height: 20,
                    },
                    consumerPrice: 30000,
                    price: 2500,
                    discountRate: 92,
                    goodsStatusText: '판매중',
                    option: { id: 305, itemList: [{ title: '용량', value: '250ml' }] },
                    packageOption: null,
                  },
                  quantity: 2,
                  consumerPriceWithQuantity: 60000,
                  priceWithQuantity: 5000,
                  isBuyable: true,
                  isQuantityChangeable: true,
                  shippingGroupName: 'delivery24',
                },
              ],
            },
          ],
          shippingGroupName: 'delivery24',
          shippingCost: 0,
          shippingPolicyText: '무료배송',
          totalSalesPrice: 5000,
        },
      ],
      totalSalesPrice: 5000,
      totalShippingCost: 0,
      orderPrice: 5000,
    },
  ],
  selectedItemCount: 7,
};
