export const checkout = {
  itemCount: 4,
  itemList: [
    {
      provider: { id: 45, name: '나이키' },
      shippingGroupList: [
        // {
        //   orderDataList: [
        //     {
        //       brand: {
        //         id: 2,
        //         name: 'nike',
        //         primaryImage: {
        //           id: 10526,
        //           path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
        //           blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
        //           width: 150,
        //           height: 40,
        //         },
        //         defaultShowRoomId: null,
        //       },
        //       goods: {
        //         id: 175,
        //         name: '나이키 조던4',
        //         primaryImage: {
        //           id: 109,
        //           path: 'goods/20210701/90bca69d-a2a1-4d22-84c9-833d58eb8b5f',
        //           blurHash: null,
        //           width: 10,
        //           height: 20,
        //         },
        //         consumerPrice: 199000,
        //         price: 199000,
        //         discountRate: 0,
        //         showRoomId: 0,
        //         code: '55y0',
        //         option: { id: 515, itemList: [{ title: '사이즈', value: '290' }] },
        //         packageOption: null,
        //       },
        //       quantity: 2,
        //       consumerPriceWithQuantity: 398000,
        //       priceWithQuantity: 398000,
        //       pcccRequired: false,
        //     },
        //   ],
        //   shippingGroupName: 'each_delivery175',
        //   shippingCost: 0,
        //   shippingPolicyText: '무료배송',
        //   isConsecutiveStay: true,
        //   totalSalesPrice: 398000,
        //   totalConsumerPrice: 398000,
        //   totalDiscountRate: 0,
        // },
        // {
        //   orderDataList: [
        //     {
        //       brand: {
        //         id: 2,
        //         name: 'nike',
        //         primaryImage: {
        //           id: 10526,
        //           path: 'brand/20211102/5c510e8a-5bed-4bd3-8043-bfca1290a257.png',
        //           blurHash: 'UdRC[6fQxuayWBayj[of~qj[Rjof%MofayWB',
        //           width: 150,
        //           height: 40,
        //         },
        //         defaultShowRoomId: null,
        //       },
        //       goods: {
        //         id: 149,
        //         name: '21ss 나이키 후드집업',
        //         primaryImage: {
        //           id: 99,
        //           path: 'goods/20210701/00fec161-cba7-4855-907a-9b0b72eda828',
        //           blurHash: null,
        //           width: 10,
        //           height: 20,
        //         },
        //         consumerPrice: 30000,
        //         price: 25000,
        //         discountRate: 17,
        //         showRoomId: 0,
        //         code: '4dy0',
        //         option: {
        //           id: 356,
        //           itemList: [
        //             { title: '사이즈', value: '100' },
        //             { title: '색상', value: '블랙' },
        //           ],
        //         },
        //         packageOption: null,
        //       },
        //       quantity: 2,
        //       consumerPriceWithQuantity: 60000,
        //       priceWithQuantity: 50000,
        //       pcccRequired: false,
        //     },
        //   ],
        //   shippingGroupName: 'delivery26',
        //   shippingCost: 0,
        //   shippingPolicyText: '무료배송',
        //   totalSalesPrice: 50000,
        // },
        {
          orderDataList: [
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
              },
              goods: {
                id: 150,
                name: '21ss 나이키 패딩',
                kind: 'REAL',
                primaryImage: {
                  id: 106,
                  path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                  blurHash: null,
                  width: 10,
                  height: 20,
                },
                consumerPrice: 30000,
                price: 25000,
                discountRate: 17,
                showRoomId: 0,
                code: '4ey0',
                option: {
                  id: 371,
                  bookingDate: 1729672281657,
                  itemList: [
                    { title: '사이즈', value: '100' },
                    { title: '색상', value: '화이트' },
                  ],
                },
                packageOption: null,
              },
              quantity: 2,
              consumerPriceWithQuantity: 60000,
              priceWithQuantity: 50000,
              pcccRequired: false,
            },
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
              },
              goods: {
                id: 150,
                name: '21ss 나이키 패딩',
                kind: 'REAL',
                primaryImage: {
                  id: 106,
                  path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                  blurHash: null,
                  width: 10,
                  height: 20,
                },
                consumerPrice: 30000,
                price: 25000,
                discountRate: 17,
                showRoomId: 0,
                code: '4ey0',
                option: {
                  id: 372,
                  bookingDate: 1698136281657,
                  itemList: [
                    { title: '사이즈', value: '105' },
                    { title: '색상', value: '화이트' },
                  ],
                },
                packageOption: null,
              },
              quantity: 1,
              consumerPriceWithQuantity: 30000,
              priceWithQuantity: 25000,
              pcccRequired: false,
            },
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
              },
              goods: {
                id: 150,
                name: '21ss 나이키 패딩',
                kind: 'REAL',
                primaryImage: {
                  id: 106,
                  path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                  blurHash: null,
                  width: 10,
                  height: 20,
                },
                consumerPrice: 30000,
                price: 25000,
                discountRate: 17,
                showRoomId: 0,
                code: '4ey0',
                option: {
                  id: 372,
                  bookingDate: 1729845081657,
                  itemList: [
                    { title: '사이즈', value: '105' },
                    { title: '색상', value: '화이트' },
                  ],
                },
                packageOption: null,
              },
              quantity: 1,
              consumerPriceWithQuantity: 30000,
              priceWithQuantity: 25000,
              pcccRequired: false,
            },
          ],
          shippingGroupName: 'delivery22',
          shippingCost: 2500,
          shippingPolicyText: '2,500원',
          isConsecutiveStay: true,
          totalSalesPrice: 75000,
          totalConsumerPrice: 75000,
          totalDiscountRate: 0,
        },
      ],
      totalSalesPrice: 523000,
      totalShippingCost: 2500,
      orderPrice: 525500,
    },
  ],
  orderer: { isIdentify: true, email: 'kai@rxc.co.kr', name: 'kai', phone: '01041114428' },
  recipient: {
    addressName: '',
    name: '심명섭',
    phone: '01041114428',
    postCode: '06158',
    address: '서울 강남구 테헤란로 427',
    addressDetail: '지하 1층 RXC',
    isPcccRequired: false,
    isAddressRequired: true,
    isShowRequestMessageDropdown: false,
  },
  payment: {
    availablePaymentTypes: ['CREDIT_CARD', 'KAKAO_PAY', 'NAVER_PAY', 'PRIZM_PAY', 'POINT'],
    savedPaymentType: null,
    usablePoint: 489750,
    pointBalance: 489750,
    pointWeight: 100,
    totalSalesPrice: 523000,
    totalShippingCost: 2500,
    orderPrice: 525500,
    isShowInstallmentDropdown: true,
    paymentBenefitList: [
      {
        paymentType: 'PRIZM_PAY',
        benefitList: [
          {
            title: null,
            content: '100만원 이상 결제시 1% 적립금 지급',
          },
        ],
      },
      {
        paymentType: 'TOSS_PAY',
        benefitList: [
          {
            title: null,
            content: '생애 첫 결제시 3% 적립',
          },
        ],
      },
      {
        paymentType: 'CREDIT_CARD',
        benefitList: [
          {
            title: '신한카드',
            content: '7만원 이상 결제시 5% 청구 할인',
          },
          {
            title: '현대카드',
            content: '3만원이상 2% 추가 할인!',
          },
        ],
      },
      {
        paymentType: 'NAVER_PAY',
        benefitList: [{ title: null, content: '무조건 3% 추가 할인' }],
      },
      {
        paymentType: 'KAKAO_PAY',
        benefitList: [{ title: null, content: '5만원 이상 결제시 카카오머니 2% 적립' }],
      },
    ],
  },
  usableGoodsCoupon: {
    '150': [
      {
        couponDownloadId: 19,
        expiredDate: 1667443344000,
        couponSale: 50000,
        totalPriceWithCouponSale: 145000,
        coupon: {
          id: 3,
          name: '유저 전시 쿠폰명',
          primaryImage: null,
          costType: 'PERCENT',
          discount: 20,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 30000,
        },
      },
      {
        couponDownloadId: 20,
        expiredDate: 1667443344000,
        couponSale: 5000,
        totalPriceWithCouponSale: 145000,
        coupon: {
          id: 4,
          name: '유저 전시 쿠폰명',
          primaryImage: null,
          costType: 'PERCENT',
          discount: 5,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 10,
        },
      },
      {
        couponDownloadId: 25,
        expiredDate: 1667443344000,
        couponSale: 5000,
        totalPriceWithCouponSale: 145000,
        coupon: {
          id: 9,
          name: '웰컴 고갱님-기간',
          primaryImage: null,
          costType: 'WON',
          discount: 5000,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 10000,
        },
      },
    ],
    '149': [
      {
        couponDownloadId: 19,
        expiredDate: 1667443344000,
        couponSale: 50000,
        totalPriceWithCouponSale: 393000,
        coupon: {
          id: 3,
          name: '유저 전시 쿠폰명',
          primaryImage: null,
          costType: 'PERCENT',
          discount: 20,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 30000,
        },
      },
      {
        couponDownloadId: 20,
        expiredDate: 1667443344000,
        couponSale: 5000,
        totalPriceWithCouponSale: 393000,
        coupon: {
          id: 4,
          name: '유저 전시 쿠폰명',
          primaryImage: null,
          costType: 'PERCENT',
          discount: 5,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 10,
        },
      },
    ],
    '148': [
      {
        couponDownloadId: 19,
        expiredDate: 1667443344000,
        couponSale: 5000,
        totalPriceWithCouponSale: 70000,
        coupon: {
          id: 3,
          name: '유저 전시 쿠폰명',
          primaryImage: null,
          costType: 'PERCENT',
          discount: 20,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 30000,
        },
      },
      {
        couponDownloadId: 20,
        expiredDate: 1667443344000,
        couponSale: 3750,
        totalPriceWithCouponSale: 71250,
        coupon: {
          id: 4,
          name: '유저 전시 쿠폰명',
          primaryImage: null,
          costType: 'PERCENT',
          discount: 5,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 10,
        },
      },
      {
        couponDownloadId: 23,
        expiredDate: 1667443344000,
        couponSale: 5000,
        totalPriceWithCouponSale: 70000,
        coupon: {
          id: 7,
          name: '애플펜슬3 초저가',
          primaryImage: null,
          costType: 'WON',
          discount: 5000,
          limitMaxSalePrice: 5000,
          limitMinPurchasePrice: 15000,
        },
      },
    ],
  },
  usableCartCouponList: [
    {
      couponDownloadId: 26,
      expiredDate: 1667443344000,
      couponSale: 5000,
      totalPriceWithCouponSale: 618000,
      coupon: {
        id: 10,
        name: '웰컴 고갱님 장바구니',
        primaryImage: null,
        costType: 'PERCENT',
        discount: 10,
        limitMaxSalePrice: 5000,
        limitMinPurchasePrice: 30000,
      },
    },
    {
      couponDownloadId: 35,
      expiredDate: 1667443344000,
      couponSale: 2000,
      totalPriceWithCouponSale: 621000,
      coupon: {
        id: 98287,
        name: '유저가 볼 쿠폰명',
        primaryImage: null,
        costType: 'PERCENT',
        discount: 40,
        limitMaxSalePrice: 2000,
        limitMinPurchasePrice: 5000,
      },
    },
    {
      couponDownloadId: 38,
      expiredDate: 1667443344000,
      couponSale: 2000,
      totalPriceWithCouponSale: 621000,
      coupon: {
        id: 98291,
        name: '유저가 볼 쿠폰명',
        primaryImage: null,
        costType: 'PERCENT',
        discount: 40,
        limitMaxSalePrice: 2000,
        limitMinPurchasePrice: 5000,
      },
    },
  ],
  seatExpiredDate: null,
};

export const calculateShipping = {
  itemCount: 3,
  itemList: [
    {
      provider: {
        id: 45,
        name: '나이키',
      },
      shippingGroupList: [
        {
          orderDataList: [
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
              },
              goods: {
                id: 150,
                name: '21ss 나이키 패딩',
                kind: 'REAL',
                primaryImage: {
                  id: 106,
                  path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                  blurHash: null,
                  width: 10,
                  height: 20,
                },
                consumerPrice: 30000,
                price: 25000,
                discountRate: 17,
                showRoomId: 0,
                code: '4ey0',
                option: {
                  id: 370,
                  itemList: [
                    {
                      title: '사이즈',
                      value: '95',
                    },
                    {
                      title: '색상',
                      value: '화이트',
                    },
                  ],
                },
                packageOption: null,
              },
              quantity: 1,
              consumerPriceWithQuantity: 30000,
              priceWithQuantity: 25000,
              pcccRequired: false,
            },
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
              },
              goods: {
                id: 150,
                name: '21ss 나이키 패딩',
                kind: 'REAL',
                primaryImage: {
                  id: 106,
                  path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                  blurHash: null,
                  width: 10,
                  height: 20,
                },
                consumerPrice: 30000,
                price: 25000,
                discountRate: 17,
                showRoomId: 0,
                code: '4ey0',
                option: {
                  id: 371,
                  itemList: [
                    {
                      title: '사이즈',
                      value: '100',
                    },
                    {
                      title: '색상',
                      value: '화이트',
                    },
                  ],
                },
                packageOption: null,
              },
              quantity: 1,
              consumerPriceWithQuantity: 30000,
              priceWithQuantity: 25000,
              pcccRequired: false,
            },
            {
              brand: {
                id: 3,
                name: '노스페이스',
                primaryImage: {
                  id: 1,
                  path: 'brand/2021/05/21/7225e89f-38d9-43bf-a40a-1c56d454c5fc',
                  blurHash: 'UF6*%skDDgWAogfRWAayDzax%jogV=ayt9j]',
                  width: 200,
                  height: 300,
                },
                defaultShowRoomId: null,
              },
              goods: {
                id: 150,
                name: '21ss 나이키 패딩',
                kind: 'REAL',
                primaryImage: {
                  id: 106,
                  path: 'goods/20210701/a1579d53-ece8-43f2-b202-2eddc367ac6e',
                  blurHash: null,
                  width: 10,
                  height: 20,
                },
                consumerPrice: 30000,
                price: 25000,
                discountRate: 17,
                showRoomId: 0,
                code: '4ey0',
                option: {
                  id: 372,
                  itemList: [
                    {
                      title: '사이즈',
                      value: '105',
                    },
                    {
                      title: '색상',
                      value: '화이트',
                    },
                  ],
                },
                packageOption: null,
              },
              quantity: 1,
              consumerPriceWithQuantity: 30000,
              priceWithQuantity: 25000,
              pcccRequired: false,
            },
          ],
          shippingGroupName: 'delivery22',
          shippingCost: 2500,
          shippingPolicyText: '2,500원',
          totalSalesPrice: 75000,
        },
      ],
      totalSalesPrice: 75000,
      totalShippingCost: 2500,
      orderPrice: 77500,
    },
  ],
  orderer: {
    isIdentify: true,
    email: 'kai@rxc.co.kr',
    name: 'kai',
    phone: '01041114428',
  },
  recipient: {
    addressName: null,
    name: '심명섭',
    phone: '01041114428',
    postCode: '06159',
    address: '서울 강남구 테헤란로 427',
    addressDetail: '지하 1층 RXC',
    isPcccRequired: false,
  },
  payment: {
    availablePaymentTypes: ['CREDIT_CARD', 'KAKAO_PAY', 'NAVER_PAY', 'PRIZM_PAY', 'POINT'],
    savedPaymentType: null,
    usablePoint: 489750,
    totalSalesPrice: 75000,
    totalShippingCost: 2500,
    orderPrice: 77500,
  },
  usableGoodsCoupon: null,
  usableCartCouponList: null,
  seatExpiredDate: null,
};
