import { PRIZM_PAY_CARD_TYPE } from '@features/prizmPay/schemas';

export const getUserPrizmPay = {
  content: [
    {
      id: 110,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 15',
      cardName: '',
      cardCode: '',
      createdDate: 1630896606000,
      isDefault: true,
      isExpired: false,
      logoPath: '/service/img_pay_default.svg',
      color: '#000000',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CHECK_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 147,
      cardNumber: '5327-****-****-1895',
      cardLast4digit: '1895',
      cardAlias: '',
      cardName: '하나카드',
      cardCode: '374',
      createdDate: 1639990060000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_hana_card.svg',
      color: '#018F7F',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.GIFT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 109,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 14',
      cardName: '우체국',
      cardCode: '71',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_post_bank.svg',
      color: '#E84333',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 108,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 13',
      cardName: '우리카드',
      cardCode: '41',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_wooricard_card.svg',
      color: '#0068B7',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 107,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 12',
      cardName: 'KB카드',
      cardCode: '381',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_kb_card.svg',
      color: '#7E7267',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 106,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 11',
      cardName: '하나카드',
      cardCode: '374',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_hana_card.svg',
      color: '#018F7F',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 105,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 10',
      cardName: '제주카드',
      cardCode: '373',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_jeju_bank.svg',
      color: '#2454C2',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 104,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 9',
      cardName: '전북카드',
      cardCode: '372',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_jeonbuk_bank.svg',
      color: '#004898',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 103,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 8',
      cardName: 'NH카드',
      cardCode: '371',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_nh_card.svg',
      color: '#0062B4',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 102,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 7',
      cardName: '씨티카드',
      cardCode: '370',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_citi_card.svg',
      color: '#064A94',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 101,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 6',
      cardName: '수협카드',
      cardCode: '369',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_suhyup_bank.svg',
      color: '#0A88D8',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 100,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 5',
      cardName: '롯데카드',
      cardCode: '368',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_lotte_card.svg',
      color: '#DE3A41',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 99,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 4',
      cardName: '현대카드',
      cardCode: '367',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_hyundai_card.svg',
      color: '#797979',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 98,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 3',
      cardName: '신한카드',
      cardCode: '366',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: false,
      logoPath: '/service/img_pay_shinhan_card.svg',
      color: '#2454C2',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 97,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: '',
      cardName: '삼성카드',
      cardCode: '365',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: true,
      logoPath: '/service/img_pay_samsung_card.svg',
      color: '#0072BC',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
    {
      id: 96,
      cardNumber: '6251-****-****-4483',
      cardLast4digit: '4483',
      cardAlias: 'test 1',
      cardName: '광주카드',
      cardCode: '364',
      createdDate: 1630896606000,
      isDefault: false,
      isExpired: true,
      logoPath: '/service/img_pay_gwangju_bank.svg',
      color: '#004898',
      isDeprecated: false,
      cardType: PRIZM_PAY_CARD_TYPE.CREDIT_CARD,
      isPossibleInstallment: false,
    },
  ],
};

export const interestFreeCard = [
  {
    cardCode: '11',
    cardCompany: '국민',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4, 5],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '31',
    cardCompany: 'BC',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4, 5, 6],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '33',
    cardCompany: '우리',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4, 5, 6],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '35',
    cardCompany: '전북',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '36',
    cardCompany: '씨티',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4, 5, 6],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '41',
    cardCompany: '신한',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4, 5, 6],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '46',
    cardCompany: '광주',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '71',
    cardCompany: '롯데',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4],
    minimumPaymentAmount: 50000,
  },
  {
    cardCode: '91',
    cardCompany: '농협',
    dueDate: 1672498799000,
    installmentFreeMonthList: [2, 3, 4, 5, 6],
    minimumPaymentAmount: 50000,
  },
];
