export const GoodsRecommendationQueryKeys = {
  SECTION_GOODS_QUERY_KEY: 'GOODS_RECOMMENDATION_SECTION_GOODS_QUERY_KEY',
  SECTION_FILTER_QUERY_KEY: 'GOODS_RECOMMENDATION_SECTION_FILTER_QUERY_KEY',
};
