import { AllSeatInfoSchema } from '../../schemas';
import { SeatInfoRequestParam, getSeatInfo } from '../seats';

const seatsSchemaMock: AllSeatInfoSchema = {
  goodsId: 24132,
  scheduleId: 17,
  scheduleAt: 1703829600000,
  userMaxPurchaseEa: 0,
  showAreaTab: true,
  mapImage: {
    id: 111,
    path: 'culture/20231114/285f22ba-ac05-49b6-bb48-1fb1f4d1f5bb.jpeg',
    blurHash: 'culture/20231114/285f22ba-ac05-49b6-bb48-1fb1f4d1f5bb.jpeg',
    width: 100,
    height: 100,
    fileType: 'IMAGE',
    extension: '0',
  },
  floatingObjects: ['PART_VIEW_SEAT', 'WHEELCHAIR_SEAT', 'STANDING'],
  areaList: [
    { scheduleId: 17, areaName: 'ED OP', orderAbleLayoutCount: 20, displayPrice: 50000, displayStage: true },
    { scheduleId: 29, areaName: 'ED VIP', orderAbleLayoutCount: 15, displayPrice: 50000, displayStage: true },
  ],
  layouts: [
    [
      {
        id: 733,
        names: ['1-1'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-1 (스탠딩석)',
        option: null,
      },
      {
        id: 734,
        names: ['1-2'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-2 (스탠딩석)',
        option: null,
      },
      {
        id: 735,
        names: ['1-3'],
        object: 'WAY_COL',
        enable: false,
        locked: false,
        selectedValue: 'ED OP 1-3 (통행로-열)',
        option: null,
      },
      {
        id: 736,
        names: ['1-4'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-4 (스탠딩석)',
        option: null,
      },
      {
        id: 737,
        names: ['1-5'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-5 (스탠딩석)',
        option: null,
      },
      {
        id: 737,
        names: ['1-5'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-5 (스탠딩석)',
        option: null,
      },
      {
        id: 758,
        names: ['1-6'],
        object: 'SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-6 (스탠딩석)',
        option: null,
      },
      {
        id: 759,
        names: ['1-7'],
        object: 'SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-7 (스탠딩석)',
        option: null,
      },
      {
        id: 760,
        names: ['1-8'],
        object: 'OTHER_COMPANY',
        enable: false,
        locked: false,
        selectedValue: 'ED OP 1-8 (A1-8)',
        option: null,
      },
      {
        id: 761,
        names: ['1-9'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-9 (A1-9)',
        option: null,
      },
      {
        id: 762,
        names: ['1-10'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 1-10 (A1-10)',
        option: null,
      },
    ],
    [
      {
        id: 738,
        names: ['2-1'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 2-1 (스탠딩석)',
        option: null,
      },
      {
        id: 739,
        names: ['2-2'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 2-2 (스탠딩석)',
        option: null,
      },
      {
        id: 740,
        names: ['2-3'],
        object: 'WAY_COL',
        enable: false,
        locked: false,
        selectedValue: 'ED OP 2-3 (통행로-열)',
        option: null,
      },
      {
        id: 741,
        names: ['2-4'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 2-4 (스탠딩석)',
        option: null,
      },
      {
        id: 742,
        names: ['2-5'],
        object: 'STANDING',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 2-5 (스탠딩석)',
        option: null,
      },
    ],
    [
      {
        id: 743,
        names: ['3-1'],
        object: 'WHEELCHAIR_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 3-1 (휠체어석)',
        option: null,
      },
      {
        id: 744,
        names: ['3-2'],
        object: 'WHEELCHAIR_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 3-2 (휠체어석)',
        option: null,
      },
      {
        id: 745,
        names: ['3-3'],
        object: 'WAY_COL',
        enable: false,
        locked: false,
        selectedValue: 'ED OP 3-3 (통행로-열)',
        option: null,
      },
      {
        id: 746,
        names: ['3-4'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 3-4 (시야제한석)',
        option: null,
      },
      {
        id: 747,
        names: ['3-5'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 3-5 (시야제한석)',
        option: null,
      },
    ],
    [
      {
        id: 748,
        names: ['4-1'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 4-1 (시야제한석)',
        option: null,
      },
      {
        id: 749,
        names: ['4-2'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 4-2 (시야제한석)',
        option: null,
      },
      {
        id: 750,
        names: ['4-3'],
        object: 'WAY_COL',
        enable: false,
        locked: false,
        selectedValue: 'ED OP 4-3 (통행로-열)',
        option: null,
      },
      {
        id: 751,
        names: ['4-4'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 4-4 (시야제한석)',
        option: null,
      },
      {
        id: 752,
        names: ['4-5'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 4-5 (시야제한석)',
        option: null,
      },
    ],
    [
      {
        id: 753,
        names: ['5-1'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 5-1 (시야제한석)',
        option: null,
      },
      {
        id: 754,
        names: ['5-2'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 5-2 (시야제한석)',
        option: null,
      },
      {
        id: 755,
        names: ['5-3'],
        object: 'WAY_COL',
        enable: false,
        locked: false,
        selectedValue: 'ED OP 5-3 (통행로-열)',
        option: null,
      },
      {
        id: 756,
        names: ['5-4'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 5-4 (시야제한석)',
        option: null,
      },
      {
        id: 757,
        names: ['5-5'],
        object: 'PART_VIEW_SEAT',
        enable: true,
        locked: false,
        selectedValue: 'ED OP 5-5 (시야제한석)',
        option: null,
      },
    ],
  ],
};

export const seatsMockApi = ({
  goodsId, // eslint-disable-line @typescript-eslint/no-unused-vars
  scheduleAt, // eslint-disable-line @typescript-eslint/no-unused-vars
  scheduleId, // eslint-disable-line @typescript-eslint/no-unused-vars
}: SeatInfoRequestParam): ReturnType<typeof getSeatInfo> =>
  new Promise((resolve) => {
    window.setTimeout(() => {
      resolve(seatsSchemaMock);
    }, 500);
  });
