import { NotificationListSchema } from '../../schemas';

export const notifications: NotificationListSchema = {
  metadata: {
    lastSeenDate: 1689571532447,
  },
  content: [
    {
      sortKey: 17248312856747132,
      templateType: 'INVITED_FRIEND_BENEFIT',
      domainType: 'COUPON_POINT',
      layout: 'DEFAULT',
      profileImage: null,
      profileAnimation: null,
      contentsImageList: [],
      message: '친구가 상품을 구매하여 적립금 5,000원을 받았습니다',
      sendDate: 1724831102206,
      landingParameter: {
        goodsId: null,
        orderId: null,
        showRoomId: null,
        liveId: null,
        storyId: null,
        auctionId: null,
        campaignId: null,
        showRoomCode: null,
        storyCode: null,
        storyType: null,
        articleId: null,
        landingType: null,
        deepLink: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
      },
    },
    {
      sortKey: 17188510360866740,
      templateType: 'CUSTOM',
      domainType: 'ETC',
      layout: 'DEFAULT',
      profileImage: {
        id: 50643,
        path: 'showroom/20220701/901ce9d8-e550-43ad-a35f-ccf7ec28058f.jpeg',
        blurHash: null,
        width: 0,
        height: 0,
        fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [],
      message: '이벤트및혜택 안드로이드에게만 보내는 메시지',
      sendDate: 1718851031579,
      landingParameter: {
        goodsId: null,
        orderId: null,
        showRoomId: null,
        liveId: null,
        storyId: null,
        auctionId: null,
        showRoomCode: null,
        storyCode: null,
        storyType: null,
        articleId: null,
        landingType: 'DEEP_LINK',
        deepLink: 'prizm://prizm.co.kr',
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 17188507562766004,
      templateType: 'CUSTOM',
      domainType: 'ETC',
      layout: 'DEFAULT',
      profileImage: null,
      profileAnimation: null,
      contentsImageList: [],
      message: '아웃링크로 보내는 메시지 ',
      sendDate: 1718850745848,
      landingParameter: {
        goodsId: null,
        orderId: null,
        showRoomId: null,
        liveId: null,
        storyId: null,
        auctionId: null,
        showRoomCode: null,
        storyCode: null,
        storyType: null,
        articleId: null,
        landingType: 'OUT_LINK',
        deepLink: null,
        outLink: 'https://mweb.prizm.co.kr',
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16935372870039756,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 416907,
        path: 'showroom/20221125/5c742060-87ee-4ac4-b206-256bd73fb555.jpeg',
        blurHash:
          '|771l@j[9FofIUWBM{WBWBofayWBayayj[j[j[j[00ay?bWB%Moft7ofofRjj[t7ofj[WBWBWBWB~qayIUofM{WBRjayWBofayRjWBayt7t7oft7M{ofofWBfQoft7WBj[ofj[ofofayRjWBayRjD%WBxuoft7WBRjt7j[',
        width: 512,
        height: 512,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1343967,
          path: 'story/20230804/e47f6892-8a6a-4ef2-8f2e-3d3319856c5f.jpeg',
          blurHash:
            '|LF=4+0i0A~9a]t5kCsR9xxn-T9gIp?DR,oJbIRn0i-n-mIpxaNKWBofxWt8E3-P-nE3oeR.s+t5IqofxWNHW=xVRnNKxWRjoft6adR.oeoIR.oK9$sk${SiRkR-xZocWXRmWY$|s.NKaekBoJayxBR-R-jFkBofWBofof',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '9월 할부 혜택 콘텐츠가 공개되었습니다',
      sendDate: 1693537278244,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21336,
        liveId: null,
        storyId: 21820,
        auctionId: null,
        showRoomCode: 'prizmevent',
        storyCode: 'bnpl2309',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16935372832799810,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 416907,
        path: 'showroom/20221125/5c742060-87ee-4ac4-b206-256bd73fb555.jpeg',
        blurHash:
          '|771l@j[9FofIUWBM{WBWBofayWBayayj[j[j[j[00ay?bWB%Moft7ofofRjj[t7ofj[WBWBWBWB~qayIUofM{WBRjayWBofayRjWBayt7t7oft7M{ofofWBfQoft7WBj[ofj[ofofayRjWBayRjD%WBxuoft7WBRjt7j[',
        width: 512,
        height: 512,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1437245,
          path: 'story/20230831/7ceba757-390e-4a5b-95d5-cf4e2ea9de4e.jpeg',
          blurHash:
            '|QOMpOO]KU$0W9s,ozslN#?ZngOIXAr:W=ocogWFA0r;ngW?s.WZWBkBn#-=S%nMs8XAj[S6jEs,NIj?ngWYkCskWYS5oHt8ofs.WAWsoKn$W=jYJEngxAX9RkW?s,jYa}t8bIn#odW?WBj[oJays8bIWXe.ofayWCofoe',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '9월 결제 혜택 콘텐츠가 공개되었습니다',
      sendDate: 1693537278243,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21336,
        liveId: null,
        storyId: 21819,
        auctionId: null,
        showRoomCode: 'prizmevent',
        storyCode: 'payment2309',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16933067116105762,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: { type: 'ON_AIR' },
      contentsImageList: [
        {
          id: 1402679,
          path: 'live/20230822/2b0a8206-6b58-41b0-ba18-145a6b33c208.jpg',
          blurHash:
            '|QHoB=U]kWMcoftSROs:og_NxBoMNGNdbIRjoLofrpxuWXxus:V@tRWVV[ofkXV@o#RjnhtRWXaes9X9V@tRjYRjWVj[ayt6R*xaWBoft7R*jYjsbIbIRiayofWCofaxofW?WBoct7WBWqadj[flRkoJofRjazofWBj[ay',
          width: 1294,
          height: 1294,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '체크인 LIVE가 시작되었습니다',
      sendDate: 1693306688599,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: 21665,
        storyId: null,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16932780854007472,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1420668,
          path: 'story/20230828/43cfb88f-5a10-4b48-a2fb-1048d2f245ed.jpeg',
          blurHash:
            '|KGTZ|xtg_NdNWX8Rit7NG00Nb-.s.xbs.sqWXs;-fjYohflM~WVR.aeax~ooeIWWWM{azbFjtocOta}RPaexYjZxYoff+S$bGr?o1kVa|W;WCf8xsWCRjkBW;j[kWn%V@xus,RlR+t6ayV@ofa}R+S4adxDkWj[niWXa}',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '이스타항공 항공권 프로모션 콘텐츠가 공개되었습니다',
      sendDate: 1693278078214,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: null,
        storyId: 21805,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: 'eastarjet2',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16932780799517636,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 49602,
        path: 'showroom/20220317/6f6af174-f37d-43e9-9d44-49b4a813c4b3.jpeg',
        blurHash:
          '|JFDqejeIGjxN0oORmoOf7oOodazWDazfQj@azfQ08j@%Iazxqazt4azj@jeRmj@t4j@j@agj@a|~iazIYj@N0j@RmjtazoOtOazN0azazodazjt92j@xqazt4fjowfjodjeRTj@xrj@j@WDj@az-+azRmkARmazWDazWD',
        width: 1440,
        height: 1439,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1418566,
          path: 'story/20230828/af60251d-2cb4-4d95-9e33-467636f9bb77.jpg',
          blurHash:
            '|fEwyCsvN7fyt1WBRrazWEoQoaa_oIWBa%j?ayj?apX0s~alRooej:a%agbUakWBayogoaj]j]j[NJjwoaWmj]jvj]axj?ocWTa*f9j=j=j?j[azRkWFWFoaoaWGj]j?j[V}k7oca$j=a$WUfPj?R%a$aya#j]awj?ofj[',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '9월 2주 차 WOWDRAW 콘텐츠가 공개되었습니다',
      sendDate: 1693278078218,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21220,
        liveId: null,
        storyId: 21806,
        auctionId: null,
        showRoomCode: 'wowdraw',
        storyCode: 'wowdraw27th',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16928747809330984,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 504496,
        path: 'showroom/20230116/86f4b5b1-dbce-4c4d-a22c-ada5ba82b4e5.jpeg',
        blurHash:
          '|URsVaoK=Iw_snsnWWsnS3sna|fQo1o1jtWWa|jt|]jtE$fQS3WWo1a|oKsnoKa|WWWWa|w_oKa|JSjtsnWWoKoKjtjta|w_a|o1o1WpfQNva|oKNvWpsnsnjtWWWWfQWpa|a|WWjtsnjtsna|WW,=a|Nva|WWjtoKfQo1',
        width: 512,
        height: 512,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1338671,
          path: 'goods/20230802/6c1f3100-3caa-41a4-9d8f-81c4ddad18cc.jpeg',
          blurHash:
            '|cJ$aLKQ}kJ.$%Rin#sDn+S$Na-5S4NexGNdsSWV%0SNEloeR%j]s:R*WB1kJDWYWXs7R*n,WYWBs+e.R.WWsnW?j?awj?Sjafn#oJs:ayWAoLWYkExDadoLj]axjYWro0n#WWbcaxoIkCs,oJfkR*w]o0n%W;WqazW=oJ',
          width: 1024,
          height: 1024,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1337721,
          path: 'goods/20230802/b738a0dc-2651-4b41-80b3-141cf5a80e2e.jpeg',
          blurHash:
            '|CK]}.=T00F_4n6S?vtQ}l0@6R|:0$i{0~Em9~A0l:yFx]4:^+?G#,-4rppc9un3o#%2-prrem,.0z$xF$nN-T#jn3RkK6%JNx9w,AXTjdWUxuwt9uVs$%X:$xM{waozkDvxEmbw=tj^V?W.s+R+E1ae-UOFoLV?WVS$SO',
          width: 1024,
          height: 1024,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1338631,
          path: 'goods/20230802/97c58d62-46ac-4a71-9bc7-e2f20e84561a.jpeg',
          blurHash:
            '|8CQ3yIS00^,9YIonikVxuM_tRa|M_xu%3WBInxb00og~XNF?Is,X8ogNFxwRPxtx]ITE1WU?HM{-p-;t79FE0tRsqM_s:RPShIUr?x]s:xbNGn~%M9YIo-=xHs:M{t8kWxusmkCbvV@WBkBM{bIbJxuRiWUozIoozn~ni',
          width: 1024,
          height: 1024,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1348323,
          path: 'goods/20230807/9961a2f2-dbcb-4f33-982a-2bf0fef3afcf.jpeg',
          blurHash:
            '|SH2jB^ks,%e%1%Mnit7bDT#b1WXS1M|RkjFbFbXD,X8tPnjoLWDbcjZs;VyoutLnPjbWEWrRlf9njRiR%jIe:aebFflWBtQjGRkX9ogk8n#oKaxR~xbs;S2R+ovocjYkBkTWCjboMofk8oej?WDofRiRjn+jYWCW;kCjH',
          width: 1000,
          height: 1000,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1339797,
          path: 'goods/20230802/5cf10393-7248-4cfa-bfe9-37881df64d90.jpeg',
          blurHash:
            '|DE:F}M]4m?cE0NbM_WZIoSI-qITRjxus,j]IU%M00IU-=Io%NxZjb%2ninQE0%h%2NFIqjX%3IUsl~Xt8ITInX8ozIUt8%gRPs:NGRjxakDkWROahD%In%NV[jGxaayozadWTS0t8jHofV@V@t8%Nn+aJbI%MM_Rlt8RP',
          width: 1024,
          height: 1024,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1348295,
          path: 'goods/20230807/73c1d908-4df7-4e2e-a213-c7ed7e289785.jpeg',
          blurHash:
            '|OH:K:w~S|XNNtozR+t6XNM?bXS0nlWBa$R,kDWC+XaxVxjcf$oIa_oKV]0=V{t7kSjFn*niaej=MdSctLo1nRahe=WEn+5WjIV{W=ozbWt3axoMm+k9V]jFocWEkDWoofE8j[brWUj[WYj]a#ofNFn,kBWEjvk8ocfikC',
          width: 1024,
          height: 1024,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1339688,
          path: 'goods/20230802/6c02849c-ccf0-43ce-b909-9ae214b7bac6.jpeg',
          blurHash:
            '|DFY$FD$4o^,9ZX9D%xvM{IUxuIUR*xaoIkCIo%M00NJ-:M{-;sSs.%2WBxbITxuxaRjIpjX%2IVnM~qxuIAIokXt7IUt7%gM{RjNGRjxaR*tRM{M{IUR,%MRjspt6ayt7t7M{NGogMxxuV@adofx]MxRO%NxuNFWEt7WB',
          width: 1024,
          height: 1024,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '웨어위럽 LIVE가 시작되었습니다',
      sendDate: 1692874773266,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21314,
        liveId: 21668,
        storyId: null,
        auctionId: null,
        showRoomCode: 'wearwelove',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16927883297590428,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 541125,
        path: 'showroom/20230213/31e228a8-2bf1-4da2-85b3-f25789219e29.jpg',
        blurHash:
          '|MN_@btPx@t6tQoeoyt6oytPayj[ayayoeWCj[kB_KayMzj[RRoeWCfjV[j[kBayoekBV[tPayV[DkaytPfQoyayoeazoex@ayj[WBayoyRRj[oyx@kBV[ayayayafj@ayj[ayj[oyayWCt6j@aff7ayfQj@ayfjj[fjay',
        width: 512,
        height: 512,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1355168,
          path: 'goods/20230809/d037b6a8-d1d5-45bc-ab9a-377155ed3ec0.jpeg',
          blurHash:
            '|@NKO|j]~qt6xbofM{j]RjWCj@axf8ofayofj[ay%Mj@M{ayWBj[ogj@ofofayj[j[fPazWCayj[%Mj[RjayWBfPj[fQj]t6fRj]j@WCazWBazj@xuj[RjazWCfPfkfRj[offQj[a|WVjtayfRj[t7fQWAf7j[fQj[j[fP',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356801,
          path: 'goods/20230809/20fba67b-89d3-489f-b06b-0187cbb3748f.jpeg',
          blurHash:
            '|qNT:tay-;fj-;xuj[Rj%M-;ofxuRjRjxuIURjof~qofM{WBM{ayj[j[RjIUj[RjWBj[WBxuofofxuj[RjayWUofj[j[off7WBWBofs;WBoffQWBofj[xbj[WBayWAj[WBj[j[WBj[ofWBj[ayayWBayayj[fQfQayfQof',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356863,
          path: 'goods/20230809/e77c7ea0-db6b-46da-9318-878ecf675c0e.jpeg',
          blurHash:
            '|vMaR]ay-;WV-;xuofRj%M-;ofxuRjM{xuIUWBj[~qofM{ayM{ayfQj[RjIUj[RjWBofWBxuoft7xuj[RjayWBj[j[j[ofayWBWBoft7WBoffQWBofj[xuj[WBayWBj[WBayayWBofofWBj[ayayWBfQj[fQayj[ayfQof',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356960,
          path: 'goods/20230809/97932137-0cda-4d21-a1ee-ee7687d74235.jpeg',
          blurHash:
            '|#Ps*IWB%Mxaxuof%MWBt7t7j[WCayayayayfQay~qt6M{WBNGf6M{ofRjRjWBofj[j[oej[a|ofM{WBkCayoej[j[j[ofxuj[WBaejZa}ayj@ayM{ayofj[j[jtofWBayogf6oLj[ayayjZazayt7j[WBfkfQWBWUj[ay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356622,
          path: 'goods/20230809/e37e9565-43b0-4649-9137-3316aeee5df0.jpeg',
          blurHash:
            '|@MHJjof-;of%Mof%2ofxuxuayayfQayfQWBfQay~qfQM{j[RjfQRjayRjWBj[ofj[ayfQoffQj[%MfQRjfQRjfQayfQj[RjfQayfQofayoffQayRjfQayayoffQofj[j[ofj[ayayj[j[j[fQayM{fQoffQoffQj[fQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356587,
          path: 'goods/20230809/2d5a6a5e-3f82-43ca-a793-50af89d13d09.jpeg',
          blurHash:
            '|,NAxGf+-;oe%Mofxuofxu%MfkWBjZWBjtWBa|f6~qoLM{a}RPfQNGj@RjM{jZofbHoea|ofjtfk%MayRjoLR*fQj@ayayoJazWBoJfkjtofa}j[WBj[ayayoffQj[j[jtkCj[f6WVoefQayj[ayIojZofbHofa|j[f6j[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357129,
          path: 'goods/20230809/c5f18b86-d03f-4e9b-8777-07739a8773d5.jpeg',
          blurHash:
            '|lQ]=?j[~XxuD%j@WBj[xuxuj[RjWBt7ofWBfQay-qoMIUWBxboMa|oLR*kBayofj[WBayoffQj[t7ayWBj[fkayoea{ayRjayxbofRjWVofayoMayayj[j[WCayoLfQayj]fQofj[WBayoLj[ayt6j[WBayoffQj[j[WB',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357147,
          path: 'goods/20230809/d5b369fd-6064-45df-a9de-d53978fa4bf9.jpeg',
          blurHash:
            '|JSPX_t7~q%MIUt7M{t7%Mxuj[WBWBt7ofRjj[ayxuj[RjWBofj[j[j[ay-;j[M{ayofj[offQayxuayRjj[WBWBt7j[WBayWBxuofRjWBofWBofWBayofj[WBayofayfQRjayxuofRjayj[fQofxuj[M{WBt7j[ofofRj',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357164,
          path: 'goods/20230809/b586407e-1d77-4b31-a10a-60907e4bccc2.jpeg',
          blurHash:
            '|tQcuBa{~qxuD%bFafayxuxuj[RjWBt7oMWBj[ay%Mj[InWBt7j[a{j[WBoffPj[j[ayfPj[azfQt7fQRjfQoffQj[fQafWBayt7ofR*ayoMayj[j[ayf6j[WVayofj[ayWBayt7j[WBayoffQfQj[fQfPfQayayoej[WB',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357182,
          path: 'goods/20230809/0069255f-4c68-456e-9301-c556dfb2687e.jpeg',
          blurHash:
            '|KSPX_of~q%MD%t7Rjof%Mxuj[WBWBofofWBj[fQofj[WBayj[j[j[j[ay%Mj[Rjayofj[fQj[ayxufQRjj[j[ayofj[WBt7ayofofWBayofayfQj[ayj[j[WBayofj[WBRjay%MofM{WBofayofj[fQfQfQWBayofofWB',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355612,
          path: 'goods/20230809/445e3a76-9350-4616-8da7-cae16276abbc.jpeg',
          blurHash:
            '|nR3QPWB~q%M9FIUxu%Mj[xuj[Rjayofj[ayj[ay-;j[IUWBxuofayWBWBj[j[ofayayj[ayayj[t7ofRjWBt7t7WBWBofayayofofWBayj[ayfQofj[WBayofofayWBj[ofayj[ofayWBj[j[ayoffQWBazj[j[fQfQay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355428,
          path: 'goods/20230809/a4588221-f320-4f08-b2c9-0f8306277d1a.jpeg',
          blurHash:
            '|gRW3iWB~q-q9FIU%M%MayxbfQWBfPoffQayj[ay-;j[IUWBxuofWBWBWBofj[ofayayj[ayf7j[t7ofRjWBt7t7WBWBoffjayofj]WBayj[f7fQofj[WBayofofayWBj[ofayj[j[ayayj[j[ayoffQayfQj[fQfQayay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355664,
          path: 'goods/20230809/694a871c-07a1-4812-a986-247579e1c1ea.jpeg',
          blurHash:
            '|tQmCrWB~q-;D%IUof%Mt7xuj[Rjayofj[j[j[ay-;j[IUayt7j[ofayWBofj[j[ayj[j[ayfQj[t7j[RjWBt7ofWBayf6WBfQt7ayWBj[fPWBj[j[j[ayWBj[ofayWBj[ofWBj[ofayRjofofWBofj[ayayj[j[fQj[fQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355649,
          path: 'goods/20230809/f0cf820f-942b-481d-9cd5-68828ef8713b.jpeg',
          blurHash:
            '|oQ,O8WB~q-;D%IUay%Mxbxuj[WAayj[f7j[j[ay%MfRIUa{s;juofayRjofj[j[ayj[j[ayfQj[t7j[RjWBs;ofWBa{ayWBj[t7ayWBofayWBofj[j[ayWBj[ofayWBj[t7WBayofayWBj[ofWBofj[WBayj[j[fQayfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355730,
          path: 'goods/20230809/482f4eb1-748d-442a-9a24-49dbbd6c46f8.jpeg',
          blurHash:
            '|xQJfmWB~q%ND%IUj[xvt7xuj[Rja|ofayj[j[ay%MjtIUayofj[ofayWBofj[j[WBj[j[ayj[j[t7j[RjWBofofayayayWBj[t7ayWBofayWBofofj[WBWBkCofayWBj[ofWBj[ofWVWBofj[WBofj[WBayj[j[ayfQfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355698,
          path: 'goods/20230809/2b5c41fb-6777-438f-a889-5c9655b7247e.jpeg',
          blurHash:
            '|tQmFyt7~qof9FWBxu%MV@xuayRjj[j[ayj[ayWB%MWBM{ofofj[ofWBayofj[j[ayj[ayaykCayt7j[RjayoffQayfQayWBj[s;WBayofWBfQofofj[WBayofj[WBfQj[t7WBj[ofWBayofayfQofj[WBayofj[ayfQfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355883,
          path: 'goods/20230809/db71e7d9-c5e4-4a56-aa97-8ee745512412.jpeg',
          blurHash:
            '|sQmFzof~qt79GofofofxuayfQofayj[j[WBayof-;j[D%ayxuj[WBj[Rjt7fQWBj[WBayofj[WBxufQM{ayt7j[ayfQayt7fQayfQayfQj[fkayayfQj[fQayfQj[fQj[offQayf6j[j[fQfQfQWBfQoffQWBfQj@fQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356070,
          path: 'goods/20230809/f80d308d-b1a0-4cbc-aced-e1c43661b28a.jpeg',
          blurHash:
            '|uQcn{of~qt7D%ofofofxuWBfQoffQj[j[WBayof-;j[D%ayxuj[ayj[Rjt7fQWBj[WBayofj[WBxuj[M{ayt7j[fQfQayt7fQayfQayfQj[j[ayayfQj[fQayfQj[fQj[offQayfQj[fQayfQfQWBfQoffQWBfQj[fQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355932,
          path: 'goods/20230809/9ee42111-a7f6-428b-bb8e-a9292290a240.jpeg',
          blurHash:
            '|vQm9jj[~qt7D%j[kCoLxuayfQoffQofj[WBayof-;j[D%WBxuj[ayj[Rjt7fQWBfQWBayofj[WBxuj[M{ayozj[jtj[ayoffQayj[ayayj[j[ayjtfQa|fQf6fQfQfQj[offQfQfQj[fQayfQj[WBfQofj[ayfQayayj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1356000,
          path: 'goods/20230809/2e41b00c-563b-4b48-96e8-5c48214dcd12.jpeg',
          blurHash:
            '|nQ].*of~qt79YofofofxuayfQoffQj[j[WBayof-;j[D%ayxuj[WBj[Rjt7fQWBj[ayayofj[WBxuj[M{ayt7j[ayfQayt7fQayfQayfQj[juayayfQj[fQayfQj[fQjuoffQayfQj[fQfQfQfQWBfQoffQWBfQj[fQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1355856,
          path: 'goods/20230809/afaca84d-c93c-414d-9ba9-4dd324cbd956.jpeg',
          blurHash:
            '|JSY{qt7~qxu9Ft7t7xut7t7j[ofayofj[WBayj[xuj[M{ayt7j[WBfPayxuayWBj[j[ayayfQof-;j[IUayxuj[WBayayt7ayofj[Rjayt7j[WBxuj@M{ayofj@offQWB%Mj[WBa|ayfQofj[WBWBfQj[fQfQfQWBayof',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357443,
          path: 'goods/20230809/903fb2bf-6af1-470d-a959-bc9692f88ca9.jpeg',
          blurHash:
            '|UR{_Wt7~Bxa9aozxZt7xZozj[oLayWVj[oLazay-oj@EMWV$*oLWCWWR*xuazWBoLofWVWBoLj]%2a|M{j[xaWVWBoLays:j@kCayaeoLj[WVa|R*jtofayWCj[j[azjsxaa|S4j[oJayW;j[jZRjfQt6fQWBjtj[ayoL',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357464,
          path: 'goods/20230809/cb42133b-ab9a-40e8-a6df-690ffd59663e.jpeg',
          blurHash:
            '|gRW0bof~qt79Fof%Mofoff7fQofj[WBayofj[ay?Ij[D%ay%Mj[Rjfjayt7fQWBayj[j[ayayfkxuj[M{ayt7j[WBayayxufQRjfQoffQWBfQj[R*fQofj[WBayj[fjj[offQj[fQayj[fkfQf7RjfQt7fQWBfQj[fQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357482,
          path: 'goods/20230809/23832858-3100-413b-bd31-7eed41f74f72.jpeg',
          blurHash:
            '|VSr.Yt7.mozH?xGtRo#kWxFfkX9jZnifkbbjZay%gbHMdnix]X8RknijEo}jZnhbIX9jFjFbIfkpIjZVrbIkqjFjEbIWWt6bHbIjYjYbbbHjFjZaKfRkWf6aefkj[f6bHkqjZr=bHX9jYnibIW;V@fQozf6WAfkfljZj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357500,
          path: 'goods/20230809/21d42160-a75c-43fb-af1d-1a4b41ae2c7d.jpeg',
          blurHash:
            '|PSZ5;t7^nt89YxX%3t8RnxWa}Wsj?n}a#bIj?ja-Xa~EJn~%3WsNGn~obg5j?sjWYSioIn$WYbakYj?aIWXkEoIadWYfk%1a#S4oIsmWYWYoIjYWAa|ogj?WBa#oej?ahohj?s+a$WFoIocWYahWAfQogj@awazj]j?j?',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357519,
          path: 'goods/20230809/6c3d9a94-b94a-485c-bb82-6afc1ff53c0a.jpeg',
          blurHash:
            '|USF-Ct7_Nt79Et7x]s:s.t7fQjZfka}f6j@fkay-=f6IAfkx]f6Rij]WXs:fkbbf6jFfkbHf6jsxtfkNGayt6fkWVf6axtRf6jEj[bbf6e.fkflWBfQoffkayf6jtfkj[s:fkbbf6jFfkflf6f6RjfQt7fQWBfQj[a|j[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357539,
          path: 'goods/20230809/2b3390ca-4459-4759-8112-637ad0692491.jpeg',
          blurHash:
            '|bRpRaoz~Bt79tozxZt6xakCj@oLayWVj[oLazaxxFjtR+WWsmoKfkWWWBt7a|WBj[ofayayoLfk%1a|Ipj[xaayWBj[azozjtn%aybHj[jZaybHt7fQRjfQoffQayjtWVs:fQbIj[jZayfkj[a}s:fQR*a|oejtWWa|jZ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357556,
          path: 'goods/20230809/45492cf2-e174-40ec-9961-f80789e5568c.jpeg',
          blurHash:
            '|qQ].*of~qs;9Fof%Mofofayazofj[WBayj[j[f6xufQM{fQt7f7WBj[ayj[fQofayWBj[j[ayayxufQM{ayt7jtWBfjayt7fQWBfQoffQayfQj[t7fQRjayt7j[WBaya|t7fQWBfQofj[ayfQj[offQWBfQj[ayayj[ay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357576,
          path: 'goods/20230809/a62d9433-aff6-4b17-9044-2d41e626436a.jpeg',
          blurHash:
            '|cSPFTs:?^o#Diw^xukWkqw^fkX9jZnibHbbjZayxtbHNGnis:X8SgnijEkXjZnhbHX8jYjYbbfkpIjZZ$bHkqjZjEbHays:bHW=jZn$bIbHjYjtt7fQRjfPoyfQayfkayozfPn%bHbHjZfQbHjZkWfRaKjZbbbHjFjZW;',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357611,
          path: 'goods/20230809/26defdf5-fa7c-4daf-a1d2-2c342a233d68.jpeg',
          blurHash:
            '|XR{_Ot6~Et89Ys+-pt8RoxVa#WGj?oHa#a~j?f8-Va}Ipjr$*WrRln~obXAj?s+WXR.ocoIWFj[oij?W8WXohocadWXkBxta}WDj?oda#agj?fjt7fRRjf6ogj[WBayj[t7jtbEa#jbj?a}a#jra$fQj=fPa$a#j=j?a#',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357629,
          path: 'goods/20230809/4c00bb01-0182-4223-a520-da93fb4c9ac4.jpeg',
          blurHash:
            '|eR{rmt7_Ns:Dht7x]ofsoozfQjYfkbHf6jsfkaytlf6R5fktRayaKj[bHsmfkbcf6jFfkbIf6jZxafkRjf6s:fkWVjZayt7fPaefkkCf6ayfkj[t7fQRjfQogfQaejtayozfQjZf6bHfkf6f6j[offQWBfQoLf6a|fkay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357203,
          path: 'goods/20230809/f7a9dd85-c184-4bf3-b4d0-9329b25f9301.jpeg',
          blurHash:
            '|gR{#.of_4t79Eof%Nt7WAt8fQWAjtogfQaxfQfk%Nj[ITayxvj[RiaykCocfQfmfQf5j@a}fQj[t7fQRjfPs;fRaxfQayaxfQt7fQWAfQoffRaxayfQj[fQayfQj[fQayogfQodfQWWfQj[fQayoefQWVfQj[fQayfQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357221,
          path: 'goods/20230809/d2db63f5-5652-4b10-aa68-fe61fc67e5c6.jpeg',
          blurHash:
            '|eRfkBof~qt74nof-;t7RjxufQRjfQoffQWBfQj[-;j[D%ay%Mj[M{ayofj[fQoffQWBj[j[fQj[t7fQRjfQt7fQWBfQayWBfQt7j[Rjayofj[WBWBfQofj[ayayj[j[ayt7fQj[fQayfQj[j[ayj[fQayfQj[j[ayfQj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357237,
          path: 'goods/20230809/18dabc3b-9735-4076-b158-b225aa219bf7.jpeg',
          blurHash:
            '|ISigQxu~qxu4.t7%MxuWBxufkfQfQjtj[ayfQj[%MfjIUayxuj[RjfQj[%MjtRjfQt7j[WBazof%Mj[M{ayxuj[WBfQayj[fQxuj[Rjayt7j[WBWBfQoffQWBfPj[fRayj[fQt7j[Rjayt7j[WBt7fQRjayogj[WBfPj[',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357271,
          path: 'goods/20230809/d3a71d76-6898-441c-b66e-688c8a8058ad.jpeg',
          blurHash:
            '|iRW0bof~qt74nj[-;t7Rjxuj[Rjayofj[WBayj[%Mj[IUay%Mj[M{ayofoffQj[jtayfQayfQj[xufkM{ayt7j[WBayj[ayfQt7j[Rjayofj[WBj[fQayfQj[fQj[fQayayfQt7j[WBayofj[WBayfQj[fQayfQj[fQay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357288,
          path: 'goods/20230809/b8acc8b6-d58d-4b33-b3b5-5d3d4a1d412f.jpeg',
          blurHash:
            '|jR:HBof_4t79Ej?%Nt7Rjt8fQWAfQogfRaxfPj[xvj[M_ayxvj[Rjayoft6fQa$fQj?j@azazj[t8j[Rjayt7j[WBayjuj=fQogj[WAayofj[axj[fQayfQfkfQj[fQayayfQt7j[WBayofj[ayayfQj[fQayfQj@fQaz',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357307,
          path: 'goods/20230809/93486135-a1a4-401d-911e-fd836571aec2.jpeg',
          blurHash:
            '|ISigQxu~qxu4nt7-;xuWBxufQj[j[ayfQfQj@j[t7fQRjayt7j[WBfQj[%Mj[Rjayt7j[Rjayof%Mj[M{ayxuj[WBayayxufQj[fQayfQoLjtayoffQWBfQj[fQj[fRayWBayxuj[M{ayt7j[WBayfQj[j[ayayj[j[ay',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357326,
          path: 'goods/20230809/2233b84e-aeb1-498c-9647-77d550f54ab7.jpeg',
          blurHash:
            '|jR:E3of_4t7D$ofxvt7s:t8fRWAayogj[V@ayof%Nj[ITayxvj[WAfQWBs.fQflj[WAayogj[WBt7fQRkfQoffQayfQa#WBfQt7j[Rjayofj[aya$fQj=fQa}fQf6fQj@offQoefQayfQj[fQayoffQWBayofj[ayfQaz',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357344,
          path: 'goods/20230809/347bc39a-2073-44c0-8e21-b2ba9e5a38f3.jpeg',
          blurHash:
            '|iRMb$of~qt79Fof%Mt7ofxuj[Rjayt7j[Rjayof-;j[D%ay%Mj[Rjf6WBj[fQofj[Rjayt7j[WBt7fQRjayoffQayfQj[WBfQt7j[Rjayofj[ayoffQWBfQj[fQayfQfQoffQj[fQayfQj[fQayoffQWBfQofjtayfQfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357361,
          path: 'goods/20230809/8d039c22-b3d3-4267-9ecd-82959589f3f9.jpeg',
          blurHash:
            '|CS$ovxu~q%M9Fxuof%M%MoffQxufQWBj[WBayt7-;j[IUayxuj[ayayRj?bj[IUfQt7ayofj[Rj%Mj[M{ayt7fQj[j[Rjt7fQxuj[Rjayofj[ayM{fQxufQRjfQj[ayoft7fQt7j[WBfQj[j[j[xufQM{ayt7fQWBj[WB',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357385,
          path: 'goods/20230809/e5c924d9-f50a-4eb3-a686-7066cfae7abb.jpeg',
          blurHash:
            '|oRysaof_4t7D#ofxvofj?t8fQWAfQogj[WAayogxvfQM_fPt8fRWAfQayt6fQa#fQfPfQj]fRaxt7fQRjfQoffQaxfQazj=fQogfRWAfPofj[WBj]fQaxfQj[fQfPfQfRayfQogfQWBfQoffQayflfQf5fQfkfQfPfQfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357405,
          path: 'goods/20230809/d386fc26-ae50-4078-b088-576d503bf606.jpeg',
          blurHash:
            '|mRC[6of~qt74nof%Mt7ayt7j[Rjayt7j[Rjayt7%Mj[IUayxuj[RjayayoffQj[fQayfQofj[aet7fQRjfQoffQWBfQfQayfQt7j[Rjayofj[WBoffQWBfQj[fQayfQfQayfQt7j[WBayofj[ayoffQayfQj[fQayfQfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357425,
          path: 'goods/20230809/ad3259ad-f42f-4369-8c37-c1ea7773cb74.jpeg',
          blurHash:
            '|CS$ovxu~q%M9Fxuxu%MxuoffQxuj[WBj[WBayt7xuj[M{ayt7j[ayfQWB-;j[M{fQt7fQayj[WB-;j[IUayxuj[WBj[Rj%MfQWBj[ayfQofj[WBWBfQofj[WBayoffQfQfQfQxuj[RjayoffQofRjfQt7fQRjfQoffQfQ',
          width: 600,
          height: 600,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '라이프로그 LIVE가 시작되었습니다',
      sendDate: 1692788323532,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21478,
        liveId: 21670,
        storyId: null,
        auctionId: null,
        showRoomCode: 'lifelog',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16927019345685188,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1360302,
          path: 'goods/20230809/88dcc1f1-d3bb-429c-bb0a-17860120231d.jpeg',
          blurHash:
            '|cE{%^xBs7oJV@jYs-oJn$.AaxxZoKofa#WBj[j[N~R+ayWqbbj[bbflWVo$fSR-fkWBj[kCWWa#IUogogofoLofjYWVofRjkDaeo0jZjFofoLj@NGWCf+WCoLWVWBoLaxaxRja#WXa#kCaeWWayogWBWBj@WVf5a}aefk',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1372627,
          path: 'goods/20230811/f6934385-7bb3-45ec-93f1-cab8e66ede6f.jpeg',
          blurHash:
            '|THy2YnNoytSR*WARkR*WXL4WBt6t7t7ogoJofj]5YxuWBRjWBkCkCkCfP$$bvR+RPRPWBWVV@jZDhNGWBn$oft7t7s:of-paJbHtRj[jsjZofbHtQjYt7f+kCWBWBaeayV@t7ofayazayWqWWa|X9t8f+jFV@ayWBWBf6',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1392285,
          path: 'goods/20230817/5f8d9118-f594-4292-aa33-106553adaf71.jpeg',
          blurHash:
            '|KE:C:M^IUNGRjWXogt7IotlM{Rixat7kBs;kCjsE4s9awogR$j]j?WBxa?wROs;W=axf8R%oLWBNNIUoM%2xuRjayt8WB%OV?Rjogafa#ogWBWBxbadbbRjbEt7jYRjj[WBf5WXt7WFWAWAoft7WDWAogogs;WAbHofj]',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1392253,
          path: 'goods/20230817/f52d694d-f066-4492-b93f-ad0d3edf0e88.jpeg',
          blurHash:
            '|kGS[k%NWBW=R*ofj[j[a#%%tSofa}j]jtaej[fRx^WAV@WBayjsoMj[ayx]RORif+bIj[j[ayWCM|V?ofogf6jtaejsj[xuWAt7kCWAj@jsj[j[W.oJt8WAbHa#bHayayaLoekCRiayfQj]j]jZayjtaef5ozbHa}ayay',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1360294,
          path: 'goods/20230809/0c7cb659-ceb0-4998-ae34-29128e7be514.jpeg',
          blurHash:
            '|OGIJw%L-5W?ofxDNeNIWB~AjaW.xWt7t7s.ofs.w?xY9vWXWBNKs,oJWB%1R+M{NIs.oLofoLWVM|R+xGsls.xZjZoMofxuxYsUjtWXWCNIWBWCR-RkofRjW=WrWXodoexZocogRkWBWBaxWBs.enR+j[oet6s.oej[oe',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1360302,
          path: 'goods/20230809/88dcc1f1-d3bb-429c-bb0a-17860120231d.jpeg',
          blurHash:
            '|cE{%^xBs7oJV@jYs-oJn$.AaxxZoKofa#WBj[j[N~R+ayWqbbj[bbflWVo$fSR-fkWBj[kCWWa#IUogogofoLofjYWVofRjkDaeo0jZjFofoLj@NGWCf+WCoLWVWBoLaxaxRja#WXa#kCaeWWayogWBWBj@WVf5a}aefk',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1372627,
          path: 'goods/20230811/f6934385-7bb3-45ec-93f1-cab8e66ede6f.jpeg',
          blurHash:
            '|THy2YnNoytSR*WARkR*WXL4WBt6t7t7ogoJofj]5YxuWBRjWBkCkCkCfP$$bvR+RPRPWBWVV@jZDhNGWBn$oft7t7s:of-paJbHtRj[jsjZofbHtQjYt7f+kCWBWBaeayV@t7ofayazayWqWWa|X9t8f+jFV@ayWBWBf6',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1392285,
          path: 'goods/20230817/5f8d9118-f594-4292-aa33-106553adaf71.jpeg',
          blurHash:
            '|KE:C:M^IUNGRjWXogt7IotlM{Rixat7kBs;kCjsE4s9awogR$j]j?WBxa?wROs;W=axf8R%oLWBNNIUoM%2xuRjayt8WB%OV?Rjogafa#ogWBWBxbadbbRjbEt7jYRjj[WBf5WXt7WFWAWAoft7WDWAogogs;WAbHofj]',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1392253,
          path: 'goods/20230817/f52d694d-f066-4492-b93f-ad0d3edf0e88.jpeg',
          blurHash:
            '|kGS[k%NWBW=R*ofj[j[a#%%tSofa}j]jtaej[fRx^WAV@WBayjsoMj[ayx]RORif+bIj[j[ayWCM|V?ofogf6jtaejsj[xuWAt7kCWAj@jsj[j[W.oJt8WAbHa#bHayayaLoekCRiayfQj]j]jZayjtaef5ozbHa}ayay',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1360294,
          path: 'goods/20230809/0c7cb659-ceb0-4998-ae34-29128e7be514.jpeg',
          blurHash:
            '|OGIJw%L-5W?ofxDNeNIWB~AjaW.xWt7t7s.ofs.w?xY9vWXWBNKs,oJWB%1R+M{NIs.oLofoLWVM|R+xGsls.xZjZoMofxuxYsUjtWXWCNIWBWCR-RkofRjW=WrWXodoexZocogRkWBWBaxWBs.enR+j[oet6s.oej[oe',
          width: 512,
          height: 512,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '체크인 LIVE가 시작되었습니다',
      sendDate: 1692701913782,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: 21669,
        storyId: null,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16926732902660098,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1400913,
          path: 'story/20230822/49568c96-70c1-4b94-bc8f-6ab2a85f2eb7.jpeg',
          blurHash:
            '|KIhZ}s:R5xtxaWCM{RjRj~WRj9ZofWCt7ogoft79Gof%MWBoeM{j[t7of4nt6-poft7RjofRjWB?bRjNGRkWBxuRjt6RjNGoft7WBafofj[WBa{M|ofofayWBayj[fQoet6ayofj[R*WBj[f7of%2WBRjj]WBofofj[j[',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '그랜드 조선 부산 프로모션 콘텐츠가 공개되었습니다',
      sendDate: 1692673278212,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: null,
        storyId: 21794,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: 'granjobuteaser',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16926154934809176,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 49602,
        path: 'showroom/20220317/6f6af174-f37d-43e9-9d44-49b4a813c4b3.jpeg',
        blurHash:
          '|JFDqejeIGjxN0oORmoOf7oOodazWDazfQj@azfQ08j@%Iazxqazt4azj@jeRmj@t4j@j@agj@a|~iazIYj@N0j@RmjtazoOtOazN0azazodazjt92j@xqazt4fjowfjodjeRTj@xrj@j@WDj@az-+azRmkARmazWDazWD',
        width: 1440,
        height: 1439,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [],
      message: '와우드로우 LIVE가 시작되었습니다',
      sendDate: 1692615486984,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21220,
        liveId: 21672,
        storyId: null,
        auctionId: null,
        showRoomCode: 'wowdraw',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16921835000253348,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1357444,
          path: 'live/20230809/0c2a6134-c2ee-496b-a541-f3e1133811de.jpg',
          blurHash:
            '|kFG5oMyn+t6WBfiafkBjsxvE0kCjufjfRfifQaz_4Rjaxj[ayf8j?fRj@%JM|a~offQayWCa{ay%NWURjjvfPj[j[j[a#s+t7WVa{juaybFazj[o#j]WBoeoeazaya{ayjEt7WBWBa#fiofj[fRbIofofa|j[f7WBaffP',
          width: 500,
          height: 500,
          // fileType: 'IMAGE',
          // extension: null,
        },
        {
          id: 1357574,
          path: 'live/20230809/f9b8ff2c-f667-4541-a4ff-83facebb31cd.jpg',
          blurHash:
            '|jD11,ozV@a#oLfRf6kCj[-@ofofazayfQfQaza{xtj?ogWUayj[f7axayt2ofaeaykBayfPj[j[xuofWAayj[j[j[j]j[ozWBkCj[ayj[j[ayayaeWBj]afj[juayf6ayt6ayWBj@ofayayj[j]t7fRayj[ayfQfkj[ay',
          width: 500,
          height: 500,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '체크인 LIVE가 시작되었습니다',
      sendDate: 1692183487817,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: 21664,
        storyId: null,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 17188485201121884,
      templateType: 'CUSTOM',
      domainType: 'ETC',
      layout: 'DEFAULT',
      profileImage: {
        id: 1465885,
        path: 'showroom/20231201/6227b979-8adc-4e4f-86c3-82cca65da816.jpg',
        blurHash:
          '|IG7b*oe}roL^js.ads.bb-Uj@S4fQR*azWqa|f6,;fQxaj@NGfQShj[NG={a|Ipa|ofj[Rjjts:xafQIpa|offQsmfQxZs9fQt7j@NGfQt6fQWBs:fQR+fQjtfQs.jtoLxajtRkfQkCfQaeayj[oJfQoLfQR*fQj[fQWC',
        width: 970,
        height: 960,
        fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [],
      message: '캠페인 관리에서 보내는 푸시',
      sendDate: 1718848500712,
      landingParameter: {
        goodsId: null,
        orderId: null,
        showRoomId: null,
        liveId: null,
        storyId: null,
        auctionId: null,
        showRoomCode: null,
        storyCode: null,
        storyType: null,
        articleId: null,
        landingType: 'DEEP_LINK',
        deepLink: 'prizm://prizm.co.kr',
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: 123,
      },
    },
    {
      sortKey: 16921548831582856,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1378084,
          path: 'story/20230814/d57ba9bc-aafb-4b1a-955e-67ef8a99710b.jpeg',
          blurHash:
            '|MH{yHtkAuMyO@kCX9xuW=TfWWM_s.xZofs9WVoKy?njiwbua0W.RjaeWBDOoKx]W=ofaeo}jFWXNGM{s;xuoMoLWVWBo0ozs:xGWCR*aeR*j]jZNGbcs:V@W;oLe.ofj]bcogt7adaeWoWAWqofVss.f+RkR*kCs:jakC',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '나트랑 푸꾸옥 웰니스 자유여행 콘텐츠가 공개되었습니다',
      sendDate: 1692154878169,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: null,
        storyId: 21786,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: 'nhatrangphuquoc',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16919820796908208,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 49602,
        path: 'showroom/20220317/6f6af174-f37d-43e9-9d44-49b4a813c4b3.jpeg',
        blurHash:
          '|JFDqejeIGjxN0oORmoOf7oOodazWDazfQj@azfQ08j@%Iazxqazt4azj@jeRmj@t4j@j@agj@a|~iazIYj@N0j@RmjtazoOtOazN0azazodazjt92j@xqazt4fjowfjodjeRTj@xrj@j@WDj@az-+azRmkARmazWDazWD',
        width: 1440,
        height: 1439,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1372363,
          path: 'story/20230811/3a739672-8447-4c05-94f1-5ce204b449a7.jpg',
          blurHash:
            '|LFX5ZW#D*amRso6bIxZRpW3RuWGj:avobj^fkod9Jt1%Gj=t1WSacRkWBR;oaRlazofWGofWZjZofaxt6j]Rof9RlofoyogbDj?f8j?j=a^j=WBj^a$N1WCoxkCt6fkWCt8j^t5ocRkaxWCayoft1WBM|k8WCfkogj[oe',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '8월 4주 차 WOWDRAW 콘텐츠가 공개되었습니다',
      sendDate: 1691982078185,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21220,
        liveId: null,
        storyId: 21792,
        auctionId: null,
        showRoomCode: 'wowdraw',
        storyCode: 'wowdraw26th',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16915500851765852,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1336124,
          path: 'story/20230801/85f034ed-4267-4b91-9b19-2fe572672fcd.jpeg',
          blurHash:
            '|EGlFeIX$,%0%3xsafxts:saxWRgj_kVWYt7M|R*?bbEe.V[R*oMInofWA~Uog9GWTa~WBt8oet7nVWnX4n+j?a{adfSofISofxvRkxuj[aekBWBD$j]x]fiaeayo0s;bHspfkxuWBV@j?M{j[fkMxWBtRxuM_oMt7Riof',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '세이지우드 기획전 프로모션 콘텐츠가 공개되었습니다',
      sendDate: 1691550078256,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: null,
        storyId: 21773,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: 'sagewoodpromo',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16908874890415144,
      templateType: 'LIVE_ON_AIR',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1322443,
          path: 'live/20230726/4869826c-fcb2-4eb3-8190-2827467c9740.jpg',
          blurHash:
            '|LL|+B-nRNrVtmZ~yEbIxu%%%Mnhs8ogs.tRjYs:U[f5o#b_M|bcR5oJRk#%M{kYtRV@kDRit7WBM{kDj]oJaJbIWrWYWB-;V@RPR*n~aeaeWCWY-;Rkj?RjoLWVjYofayoff6aej[ofWVa}a#fPT1jYn$n$WBf5bIWBoK',
          width: 1440,
          height: 1440,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '체크인 LIVE가 시작되었습니다',
      sendDate: 1690887482033,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: 21662,
        storyId: null,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: null,
        storyType: null,
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16908516822895648,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 416907,
        path: 'showroom/20221125/5c742060-87ee-4ac4-b206-256bd73fb555.jpeg',
        blurHash:
          '|771l@j[9FofIUWBM{WBWBofayWBayayj[j[j[j[00ay?bWB%Moft7ofofRjj[t7ofj[WBWBWBWB~qayIUofM{WBRjayWBofayRjWBayt7t7oft7M{ofofWBfQoft7WBj[ofj[ofofayRjWBayRjD%WBxuoft7WBRjt7j[',
        width: 512,
        height: 512,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1321520,
          path: 'story/20230725/df8f3a2c-d218-4ca8-800a-c43714d1441d.jpeg',
          blurHash:
            '|VPPruX:PEwGW9ocozslS*?Gi^S+bdnMbIoJogWYEnngi^bcoLWsWBkBn#-;XAaIngkXj[S6jEocNIa{e,W=kCn}WYWYn#t8kCoeWAW?oKn$W=f5N}jEsjbcV[bJocjYa}t8bInhoKW?WBfjoJayn#bIWXe.ofaxWCofj[',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '8월 할부 혜택 콘텐츠가 공개되었습니다',
      sendDate: 1690851678167,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21336,
        liveId: null,
        storyId: 21767,
        auctionId: null,
        showRoomCode: 'prizmevent',
        storyCode: 'bnpl2308',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16908516797204748,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 416907,
        path: 'showroom/20221125/5c742060-87ee-4ac4-b206-256bd73fb555.jpeg',
        blurHash:
          '|771l@j[9FofIUWBM{WBWBofayWBayayj[j[j[j[00ay?bWB%Moft7ofofRjj[t7ofj[WBWBWBWB~qayIUofM{WBRjayWBofayRjWBayt7t7oft7M{ofofWBfQoft7WBj[ofj[ofofayRjWBayRjD%WBxuoft7WBRjt7j[',
        width: 512,
        height: 512,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1320237,
          path: 'story/20230725/89284a08-782a-4902-b3d7-d71a7cdb185a.jpeg',
          blurHash:
            '|UPPx;X:T5wFX2s,kDn$XB.6nNWcXAnfbIj@kDa$EUngjCX9oLbJaebHjE-;XAV=ngkXj[W?jEf$RlayV?j]ofjXWYbIjXxbj]oejEbJaze.kCjrI_jExUbcRkbJocjYj[WabIxUj@R:jYodayj?aKf+kBWBbIobjZa$j[',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '8월 결제 혜택 콘텐츠가 공개되었습니다',
      sendDate: 1690851678165,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21336,
        liveId: null,
        storyId: 21766,
        auctionId: null,
        showRoomCode: 'prizmevent',
        storyCode: 'payment2308',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16905132794950374,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 908327,
        path: 'showroom/20230413/0ab5b027-4304-4a0d-9b1b-859bcac2b018.jpeg',
        blurHash:
          '|LRW0bof-;%M-;xuWBWBM{xuWBayofj[j[WBayWB~qofD%RjIUayoft7xut7t7j[RjWBayt7j[ofD%fQxuayt7j[j[ayWBt7WBj[ofj[ofWBj[WBj[WBWBoft7fQWBWBWB%Mj[Rjj[j[WBj[WBoft7ofayWBWBWBj[ofof',
        width: 1440,
        height: 1440,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1327085,
          path: 'story/20230727/3d4e6654-c7b7-414a-ae76-d13e57e744d8.jpeg',
          blurHash:
            '|fK^y,-=t7IT%MWCWBoLt7?wxukCNGt7f6WBofayShRPV@ozWBoeWXj[WB$%Rkaet7Rjj[j[j@j]x]WCW=t7WBazoKj[WCt7RjaeoLWCj[j[f6aekCayjsazaej[flWBofofofaykCa}azoLWBofoLWWayoJWVj@j[ayf6',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '여름철 완벽한 스킨케어의 시작 콘텐츠가 공개되었습니다',
      sendDate: 1690513278236,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21530,
        liveId: null,
        storyId: 21759,
        auctionId: null,
        showRoomCode: 'fmproject',
        storyCode: 'fmproject2',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16902541075406390,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1312320,
          path: 'story/20230721/6b8a58ac-56fc-4167-b127-99dff191ce52.jpeg',
          blurHash:
            '|7Kde+-A0PNYQ,x^4:o#V@ElDh8_.9?bxvxXM{xuVFys-oMJEhI9-p$yM{Io%MxDD$t7j]W?tRV?0gVX-opI-oxuIUIrf6?bIA%Mx^9ExvIps8xvR3R+f,xuRkM{t8s8xuIT-;%gD%o#IUs8o#M_DiR+ozxYo#bIV@ogxt',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: 'JW 메리어트 제주 프로모션 콘텐츠가 공개되었습니다',
      sendDate: 1690254078331,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: null,
        storyId: 21755,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: 'checkin44',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
    {
      sortKey: 16902540966046504,
      templateType: 'SHOWCASE_CONTENTS',
      domainType: 'FOLLOWING',
      layout: 'DEFAULT',
      profileImage: {
        id: 134197,
        path: 'showroom/20220503/2e95cd95-c0f2-4f4c-9d64-0364647e185b.jpeg',
        blurHash:
          '|7Kwh5ROIU-=Di-pofV@xuxaWBj]ofWBofj[axof00%M%MIU.8M{WBxuM{xatRV@RjtRRjayogRj_NM_Mxx]IAt8ofRit7xaM{t7xuM{t8j[RjtR9Et7xuRjxvWBaxofWBxuxuRjM{xuRjayozRP%gayRjj[Rjayj[j[ay',
        width: 513,
        height: 513,
        // fileType: 'IMAGE',
        // extension: null,
      },
      profileAnimation: null,
      contentsImageList: [
        {
          id: 1320136,
          path: 'story/20230725/1672c8db-84aa-4b9c-bb35-6b3575883920.jpeg',
          blurHash:
            '|ZE2wYENRjj[ofoeNGoekC~VIpofoeWCs:WCoLfR-pR,ofj[Rjayofj[WBbcf7WBfRoeWVoLj[WVI;s.ayWVoeayjsWVj[I;s.fPayoLayfQayj[Ncaeoej[j[a}j[jtfPozjtfkazayayayayj[ofayazj[j[j[oeayay',
          width: 1024,
          height: 768,
          // fileType: 'IMAGE',
          // extension: null,
        },
      ],
      message: '동남아 호텔 리조트 프로모션 콘텐츠가 공개되었습니다',
      sendDate: 1690254078332,
      landingParameter: {
        deepLink: null,
        landingType: null,
        goodsId: null,
        orderId: null,
        showRoomId: 21293,
        liveId: null,
        storyId: 21762,
        auctionId: null,
        showRoomCode: 'checkin',
        storyCode: 'nearcation1',
        storyType: 'TEASER',
        articleId: null,
        outLink: null,
        liveRaffleItemId: null,
        goodsCode: null,
        orderItemOptionIdList: null,
        campaignId: null,
      },
    },
  ],
  nextParameter: 'size=20&sortKey=16902540966046504',
};
